// COMMIT LINT CONFIGS ACORDING TO: https://commitlint.js.org/#/reference-configuration?id=configuration-object-example

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-empty': [0, 'never'],
    'type-empty': [0, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'codestyle',
        'perf',
        'prune',
        'bugfix',
        'hotfix',
        'feature',
        'docs',
        'deploy',
        'ui',
        'init',
        'tests',
        'security',
        'tags',
        'lint',
        'wip',
        'fixci',
        'downgrade',
        'upgrade',
        'depver',
        'ci',
        'analytics',
        'refactor',
        'depadd',
        'deprm',
        'config',
        'devscripts',
        'i18n',
        'typo',
        'fraky',
        'revert',
        'merge',
        'binary',
        'contract',
        'relocate',
        'license',
        'breaking',
        'assets',
        'a11y',
        'comment',
        'gibberish',
        'text',
        'db',
        'addlogs',
        'rmlogs',
        'contrib',
        'ux',
        'arch',
        'responsive',
        'mock',
        'joke',
        'gitignore',
        'snapshots',
        'poc',
        'seo',
        'types',
        'seed',
        'flags',
        'detect',
        'animation',
        'deprecate',
        'auth',
        'fix',
        'explore',
        'clean',
        'fall'
      ]
    ]
  }
};
